### PR TITLE
fix AE, PK and SUBJ data types

### LINKED ISSUE #101: Fix data types in AE, PK and SUBJ
## Current Behavior

Several columns throw a warning when loading the AE, PK and SUBJ mapped data due to type errors. PK not shown below.

Image

## Expected Behavior

No warnings should pop up when data is properly formatted

## Possible Solution

edit the following to have the correct data types:
- AE   
  - aetoxgr: integer
- SUBJ
  - timeontreatment: integer
  - agerep: integer
- PK
  - pkdat: Date

## Steps to Reproduce

1.
2.
3.
4.

## QC Approach

In addition to standard QC (e.g., code reviews, automated checks) the following QC measures will be implemented:

[X] Update existing Qualification/Unit Tests 
[ ] New Unit Tests

### PR DESCRIPTION
**Pull request by lauramaxwell**
## Overview

update data types for three columns in AE and SUBJ that were throwing warnings during mapping pipeline.

## Connected Issues

- Closes #101

### CODE REVIEW

File: tests/testthat/test-qual_T1_1.R [hunk 1]
```diff
@@ -130,7 +130,7 @@ test_that("Qual: mappings now done by individual domain, test that inputs and ou
   iwalk(
     mapped_p3_yaml,
     ~ expect_true(all(
-      names(flatten(.x$spec)) %in%
+      setdiff(names(flatten(.x$spec)), "db_lock_dt") %in%
```
Comment (samussiah) [inline tests/testthat/test-qual_T1_1.R:133]: `db_lock_dt` was throwing warnings in `gsm.endpoints` too - guessing any data simulated with `gsm.datasim` will be missing the new column?

Comment (lauramaxwell) [reply tests/testthat/test-qual_T1_1.R:133]: yeah, that's right. i'll make an issue to revert this setdiff once we update datasim/lSource this quarter.

Comment (zdz2101) [reply tests/testthat/test-qual_T1_1.R:133]: yea I didn't realize the ripple effect, but the gsm.datasim needs to be updated, the current gsm.datasim@qtl_tabletop branch contains it

Comment (lauramaxwell) [reply tests/testthat/test-qual_T1_1.R:133]: @samussiah, @zdz2101 - I've added an [issue](https://github.com/Gilead-BioStats/gsm.mapping/issues/112) to remove this `setdiff()` once simulated data has been updated at the end of the quarter. would be nice to get this in before that to quiet down a lot of the warnings we get during ingest/runworkflow.

**Review by zdz2101 — APPROVED** [review]
LGTM

**Review by samussiah — APPROVED** [review]
